Added decorator to check latest PyPi version + cosmetic changes

diff --git a/tfmake/Makefile.aws b/tfmake/Makefile.aws
--- a/tfmake/Makefile.aws
+++ b/tfmake/Makefile.aws
@@ -37,10 +37,14 @@ endif
 aws_account_info:
 	$(eval AWS_ACCOUNT_ID=$(shell aws sts get-caller-identity --output text --query 'Account'))
 	$(eval AWS_ACCOUNT_ALIAS=$(shell aws iam list-account-aliases --output text --query 'AccountAliases[*]'))
+	
+	@if [ ! -f terraform.tf ]; then echo "[ERROR] Expecting terraform.tf in directory '$(PWD)'"; exit 1; fi;
+	$(eval CURRENT_TF_KEY=$(shell cat terraform.tf | grep key | sed 's/["[:space:]]//g' | cut -d "=" -f 2 | cut -d "#" -f 1))
 
 tf_init: aws_account_info
 	@if [ -e .terraform/environment ]; then rm .terraform/environment; fi;
 	@if [ -e .terraform/terraform.tfstate ]; then rm .terraform/terraform.tfstate; fi;
+
 	@terraform init -backend-config 'workspace_key_prefix=$(AWS_ACCOUNT_ALIAS)'
 
 tf_options:
@@ -50,13 +54,20 @@ tf_workspace:
 	@terraform workspace select $(env) 2> /dev/null || terraform workspace new $(env)
 
 tf_confirm: aws_account_info
-	@printf "\nUsing workspace '$(env)' on '$(AWS_ACCOUNT_ALIAS)'.\n"
+	@printf "\nUsing the following details:\n\n"
+	@printf " - workspace: $(env)\n"
+	@printf " - account: $(AWS_ACCOUNT_ALIAS)\n"
+	@printf " - key: $(AWS_ACCOUNT_ALIAS)/$(CURRENT_TF_KEY)\n\n"
+
 	@if [ -z $$TFMAKE_AGREE ]; then \
 		echo "Press [ENTER] to continue or [CTRL-C] to stop." && read INPUT; \
 	fi
 
 update: ## Update terraform modules and providers
 	@terraform init -upgrade=true -no-color
+
+update_modules: ## Only update modules
+	@terraform get -update -no-color
 
 select: tf_validate tf_init tf_workspace ## Select and initialize terraform workspace (aka 'stage')
 	@printf $(GREEN)"\n\n>>> Now using Terraform workspace '$(env)' on AWS account '$(AWS_ACCOUNT_ALIAS)' ...\n"$(WHITE)
@@ -65,10 +76,10 @@ show: aws_account_info ## Show current terraform workspace
 	$(eval CURRENT_WORKSPACE=$(shell terraform workspace show))
 	@printf $(GREEN)"\nCurrently using Terraform workspace '$(CURRENT_WORKSPACE)' on AWS account '$(AWS_ACCOUNT_ALIAS)' ...\n"$(WHITE)
 
-plan: tf_validate tf_options tf_confirm ## Generate and show an execution plan
+plan: tf_validate tf_options update_modules tf_confirm ## Generate and show an execution plan
 	@terraform $@ $(TF_OPTIONS) $(args)
 
-apply: tf_validate tf_options tf_confirm ## Builds or changes infrastructure
+apply: tf_validate tf_options update_modules tf_confirm ## Builds or changes infrastructure
 	@terraform $@ $(TF_OPTIONS) -no-color $(args)
 	@terraform output -no-color -json 2> /dev/null | jq 'with_entries(.value |= .value)' > tf.${env}.outputs.json
 
