Added new target apply-plan

diff --git a/tfmake/Makefile.aws b/tfmake/Makefile.aws
--- a/tfmake/Makefile.aws
+++ b/tfmake/Makefile.aws
@@ -96,6 +96,15 @@ apply: tf_validate tf_options tf_confirm ## Builds or changes infrastructure
 	fi
 	@terraform output -no-color -json 2> /dev/null | jq 'with_entries(.value |= .value)' > tf.${env}.outputs.json
 
+apply-plan: tf_validate tf_confirm ## Builds or changes infrastructure using a saved terraform plan
+	@terraform $@ -no-color $(args) ; \
+	retVal=$$?; \
+	if [ $$retVal -ne 0 ]; then \
+		echo "terraform failed with status $$retVal"; \
+		exit 1; \
+	fi
+	@terraform output -no-color -json 2> /dev/null | jq 'with_entries(.value |= .value)' > tf.${env}.outputs.json
+
 destroy: tf_validate tf_options tf_confirm ## Destroy Terraform-managed infrastructure
 	@terraform $@ $(TF_OPTIONS) -no-color $(args)
 
