Fixed cross-platform read + fixing azurerm state backend configuration

diff --git a/tfmake/Makefile.azure b/tfmake/Makefile.azure
--- a/tfmake/Makefile.azure
+++ b/tfmake/Makefile.azure
@@ -40,8 +40,10 @@ azure_info:
 tf_init: azure_info
 	@if [ -e .terraform/environment ]; then rm .terraform/environment; fi;
 	@if [ -e .terraform/terraform.tfstate ]; then rm .terraform/terraform.tfstate; fi;
-	$(eval WORK_DIR=$(shell basename $$PWD))
-	@terraform init -backend-config 'key=$(ARM_ACCOUNT_ALIAS)/$(WORK_DIR)/$(env).terraform.tfstate'
+	@if [ ! -f terraform.tf ]; then echo "[ERROR] Expecting terraform.tf in directory '$(PWD)'"; exit 1; fi;
+
+	$(eval CURRENT_TF_KEY=$(shell cat terraform.tf | grep key | sed 's/["[:space:]]//g' | cut -d "=" -f 2 | cut -d "#" -f 1))
+	@terraform init -backend-config 'key=$(ARM_ACCOUNT_ALIAS)/$(CURRENT_TF_KEY)'
 
 tf_options:
 	$(if $(wildcard vars/$(env).tfvars), $(eval TF_OPTIONS := $(TF_OPTIONS) -var-file "vars/$(env).tfvars"))
@@ -49,10 +51,10 @@ tf_options:
 tf_workspace:
 	@terraform workspace select $(env) 2> /dev/null || terraform workspace new $(env)
 
-tf_confirm: aws_account_info
-	@echo "\nUsing workspace '$(env)' on '$(AWS_ACCOUNT_ALIAS)'.\n"
+tf_confirm: azure_info
+	@echo "\nUsing workspace '$(env)' on '$(ARM_ACCOUNT_ALIAS)'.\n"
 	@if [ -z $$TFMAKE_AGREE ]; then \
-		read -p "Press [ENTER] to continue or [CTRL-C] to stop."; \
+		echo "Press [ENTER] to continue or [CTRL-C] to stop." && read INPUT; \
 	fi
 
 update: ## Update terraform modules and providers
